sudo: required

services:
  - docker

language:
  - groovy
jdk:
  - oraclejdk8

before_script:
  - docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_KEY} -e ${DOCKER_HUB_EMAIL}

script:
  - ./gradlew pushImage -i

after_script:
  - docker logout
